### ISSUE TITLE
Colours are off on some images on Win FF, Chrome, IE

### ISSUE THREAD

**Issue by wohali** [michellephung/Fauxton-Visual-Guide#1]
Screenshot s from Firefox:
![badcolours](https://cloud.githubusercontent.com/assets/112292/8418187/68beb54e-1e7f-11e5-8ae1-8d3d55050ced.png)

The affected pictures (that have the brownish tint) are login.png, config.png cors.png, add-admin.png and verify.png. The rest all have the bright red.

Chrome shows the same colour variation. In IE the colour variation is still there but less pronounced.

It must be something specific in the png file and how it renders in the browser, because the colours look correct when downloaded and opened in a photo editing tool (here, Paint.NET)

**Comment by michellephung** [comment]
fixed!
